# Generated by Django 4.1.1 on 2022-11-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='followie',
        ),
    ]
