# Generated by Django 4.1.1 on 2022-11-18 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_user_follow_followie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(null=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
