# Generated by Django 4.1.1 on 2022-11-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
    ]
